on:
  schedule:
    - cron: '0 7 * * *' 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest
    permissions:
      contents: write
      packages: write 
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - id: repo 
        name: Repo Checkout
        uses: actions/checkout@v2
      

      - id: python
        name: Python Setup & Packages Installation
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pip'
      - run: pip install -r requirements.txt

      - id: jupyter 
        name: Jupyter Notebook Execution
        run: jupyter execute polls.ipynb
        shell: bash 

 # Add new files in folder, commit along with other modified files, push
      - id: commit
        name: Commit files
        run:
          git config --local user.name actions-user

          git config --local user.email "actions@github.com"

          git add all_polls.csv

          git commit -am "Voting Intention $(date)"

          git push origin main

        env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}

          username: github-actions
